apiVersion: v1
kind: Template
metadata:
  name: selinon-secret
  labels:
    app: selinon
    template: selinon-secret
  annotations:
    description: Secrets used within Selinon demo deployment.
    openshift.io/display-name: Selinon secrets
    version: 1.0.0
    tags: poc,selinon,secrets,credentials
    template.openshift.io/documentation-url: https://github.com/selinon
    template.openshift.io/long-description: This template defines secrets required for Selinon demo application.
    template.openshift.io/provider-display-name: Fridolin Pokorny

objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: selinon
    labels:
      app: selinon
  stringData:
    api-app-secret: ${API_APP_SECRET}
    s3-key-id: ${S3_KEY_ID}
    s3-secret-key: ${S3_SECRET_KEY}
    mongo-password: ${MONGO_PASSWORD}
    mongo-admin-password: ${MONGO_ADMIN_PASSWORD}
    postgres-password: ${POSTGRES_PASSWORD}

parameters:
  - description: A secret application key for API server (Flask's app secret).
    displayName: API server secret key.
    required: true
    name: API_APP_SECRET

  - description: Key ID used to access S3 API.
    displayName: S3 key ID.
    required: true
    name: S3_KEY_ID
    default: PCOMYKL7WQ8ZCESM0TH9

  - description: Secret key to access S3 API.
    displayName: S3 secret key.
    required: true
    name: S3_SECRET_KEY
    default: 'aHDakH5CK/5LPM2kDnQX6BAlp9CyIOI9V3E+aU+S'

  - description: MongoDB password.
    displayName: MongoDB password.
    required: true
    name: MONGO_PASSWORD

  - description: MongoDB admin password.
    displayName: MongoDB admin password.
    required: true
    name: MONGO_ADMIN_PASSWORD

  - description: PostgreSQL password.
    displayName: PostgreSQL password.
    required: true
    name: POSTGRES_PASSWORD

